CREATE DATABASE IF NOT EXISTS twich_analytics;
USE twich_analytics;

CREATE TABLE IF NOT EXISTS USUARIOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS API_KEY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT,
    API_KEY VARCHAR(100) UNIQUE NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SESSION_TOKENS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    TOKEN VARCHAR(100) UNIQUE NOT NULL,
    EXPIRATION TIMESTAMP NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cached_topsofthetops (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
