CREATE DATABASE IF NOT EXISTS twich_analytics;
USE twich_analytics;

CREATE TABLE IF NOT EXISTS USUARIOS(
      ID INT AUTO_iNCREMENT PRIMARY KEY,
      EMAIL VARCHAR(50) UNIQUE NOT NULL,
      FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS API_KEY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT,
    API_KEY VARCHAR(100) UNIQUE NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);
