CREATE DATABASE IF NOT EXISTS twich_analytics;
USE twich_analytics;

CREATE TABLE IF NOT EXISTS USUARIOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS API_KEY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT,
    API_KEY VARCHAR(100) UNIQUE NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SESSION_TOKENS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    TOKEN VARCHAR(100) UNIQUE NOT NULL,
    EXPIRATION TIMESTAMP NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS top_videos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id TEXT NOT NULL,
    game_name TEXT NOT NULL,
    user_name TEXT NOT NULL,
    total_videos INTEGER NOT NULL,
    total_views INTEGER NOT NULL,
    most_viewed_title TEXT NOT NULL,
    most_viewed_views INTEGER NOT NULL,
    most_viewed_duration TEXT NOT NULL,
    most_viewed_created_at TEXT NOT NULL,
    cached_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
